services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1003:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production